/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import javax.swing.*;
import java.math.BigDecimal;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author HK
 */
public class Withdraw extends javax.swing.JFrame {

    private Locale locale = new Locale("vi", "VN");
    private NumberFormat n = NumberFormat.getCurrencyInstance(locale);
    private RMIClient client;
    //private String cardNo = "1234567890";

    /**
     * Creates new form Withdraw
     */
    public Withdraw() {
        try {
            client = new RMIClient();
            initComponents();
            setLocationRelativeTo(null);
            tfBalance.setText(String.valueOf(n.format(client.getBank().getAccount(Login.userInfo.get(1)).getBalance())));

        } catch (RemoteException ex) {
            Logger.getLogger(Withdraw.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Withdraw.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btWithdraw = new javax.swing.JButton();
        btBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfBalance = new javax.swing.JTextField();
        tfAmount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Số tiền cần rút : ");

        btWithdraw.setText("Rút");
        btWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btWithdrawActionPerformed(evt);
            }
        });

        btBack.setText("Quay lại");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        jLabel4.setText("Số dư hiện tại : ");

        tfBalance.setEditable(false);
        tfBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBalanceActionPerformed(evt);
            }
        });

        tfAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAmountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel3))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tfBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(71, 71, 71)
                                                .addComponent(btWithdraw)))
                                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btBack)
                                        .addComponent(btWithdraw))
                                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        new GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_btBackActionPerformed

    private void tfBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBalanceActionPerformed

    private void reset() {
        tfAmount.setText("");
    }

    //check input is numberic.
    public static boolean isNumeric(String strNum) {
        if (strNum.length() > 13) {
            return false;
        } else {
            return strNum.matches("-?\\d+(\\.\\d+)?");
        }
    }

    private void btWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btWithdrawActionPerformed
        String codeshow = "";
        if (isNumeric(tfAmount.getText())) {
            try {
                ArrayList<String> code;
                System.out.println(Login.userInfo);
                System.out.println(Login.userInfo.get(1) + tfAmount.getText());
                code = client.getBank().withdraw(Login.userInfo.get(1), new BigDecimal(tfAmount.getText()));
                if (code.size() > 0) {
                    for (int i = 0; i < code.size(); i++) {
                        codeshow = code.get(i) + "\n";
                    }
                    JOptionPane.showMessageDialog(null, codeshow, "Warning",
                            JOptionPane.WARNING_MESSAGE);
                } else {
                    tfBalance.setText(String.valueOf(n.format(client.getBank().getAccount(Login.userInfo.get(1)).getBalance())));
                    JOptionPane.showMessageDialog(null, "Thành công", "Success",
                            JOptionPane.INFORMATION_MESSAGE);
                }
                reset();
            } catch (RemoteException ex) {
                Logger.getLogger(Withdraw.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Withdraw.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Mời nhập đúng số tiền!", "Warning",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btWithdrawActionPerformed

    private void tfAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAmountActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btWithdraw;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tfAmount;
    private javax.swing.JTextField tfBalance;
    // End of variables declaration//GEN-END:variables

}
